# Pandas数据处理120题知识点总结
## 第一章 创建DataFrame及Numpy基础操作

---
  
　ID：wlong
　数据分析爱好者、目前小白一枚
　邮箱：wlong826@163.com
　CSDN：**[【数分小白龙】](https://blog.csdn.net/qq_38230663)**
　和鲸社区：**[【wlong】](https://www.heywhale.com/home/user/profile/5f0a61d72be199002c073935)**
　如果有不完善的地方，欢迎小伙伴评论区留言！
　最近博客、和鲸每周都会有所更新，欢迎大家**关注点赞分享**哦！
 
---

　本文的CSDN链接：[【一、创建DataFrame及Numpy基础操作】](https://blog.csdn.net/qq_38230663/article/details/116395007?spm=1001.2014.3001.5501)
	
　如果有想学习爬虫的小伙伴，可以看这里：[【零基础入门Python爬虫--豆瓣、58同城、安居客等】](https://www.heywhale.com/mw/project/60be1fa8acdcb3001707b133)
 
  　关于总结更详细的配套习题案例，看这👉：[【和鲸训练营第一期——Pandas基础】](https://www.heywhale.com/home/competition/60c086d8565cca001731537f)
	

In [1]:
import pandas as pd
import numpy as np

# 1. 创建DataFrame:

### (1) 字典法

In [2]:
data = {"grammer":['Python', 'C', 'Java', 'GO', 'css', 'SQL', 'PHP', 'Python'],
       "score":[1.0, 2.0, 6.0, 4.0, 5.0, 6.0, 7.0, 10.0]}
df = pd.DataFrame(data)
df

grammer  score
0  Python    1.0
1       C    2.0
2    Java    6.0
3      GO    4.0
4     css    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0

### (2) Series

In [3]:
df2 = pd.DataFrame(pd.Series(np.random.randint(1, 10, 100)), columns = ['xxx'])
df2.head()

xxx
0    4
1    8
2    4
3    4
4    1

### (3) 先创建空的dataframe，再加入列

In [4]:
df3 = pd.DataFrame()
df3['ID'] = [0,1,2]
df3

ID
0   0
1   1
2   2

###  (4) 以现有的dataframe列新建一个dataframe

In [5]:
df4 = pd.DataFrame(columns = df.columns.tolist())
df4

Empty DataFrame
Columns: [grammer, score]
Index: []

## 2. Numpy

### (1) 随机生成20个0-100的随机整数：Numpy.random.randint()

In [6]:
np.random.randint(0, 100, 20)

array([82, 98, 97, 87, 69, 72, 66, 61, 15, 62,  5, 28, 44, 40, 58, 92,  5,
       48, 86, 28])

### (2) 生成20个0-100固定步长的数：Numpy.arange()

- np.arange()函数分为一/两/三个参数三种情况：
	- 1）一个参数时，参数值为终点，起点取默认值0，步长取默认值1。
	- 2）两个参数时，第一个参数为起点，第二个参数为终点，步长取默认值1。
	- 3）三个参数时，第一个参数为起点，第二个参数为终点，第三个参数为步长。其中步长支持小数

In [7]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### (3) 生成20个指定分布（如标准正态分布）的数：Numpy.random.normal()

In [8]:
np.random.normal(0, 1, 20)

array([ 1.8815326 ,  0.88428526, -0.31475697,  1.09001515,  0.35559398,
       -0.77496026,  0.05032371,  0.48866403, -0.49927103,  2.30405094,
       -0.46014544, -1.09368926,  0.27466879, -0.30502541,  0.25816164,
        0.28607551, -0.5484942 , -0.28864237, -1.48522615,  0.45633582])

### (4) 提取score列中可以整除5的数字位置：Numpy.argwhere()

In [9]:
np.argwhere(np.array(df['score'] % 5 == 0))

array([[4],
       [7]])

### (5) 查看两列值相等的行号：Numpy.where()

- np.where()用法：
    - np.where(condition, x, y)： # 满足条件(condition)，输出x，不满足输出y。
    - np.where(condition)：只有条件 (condition)，没有x和y，则输出满足条件 (即非0) 元素的坐标 (等价于numpy.nonzero)。当条件成立时，where返回的是每个符合condition条件元素的坐标,返回的是以元组的形式。


- 相关资料：
    - https://www.cnblogs.com/massquantity/p/8908859.html
    - https://blog.csdn.net/lens___/article/details/83896645

In [10]:
df['cycle'] = [2.0, 3.0, 6.0, 3.0, 5.0, 2.0, 7.0, 5.0]

In [11]:
#方法一：值相等
df[df['score'] == df['cycle']].index
 
#方法二：np.where()
np.where(df.score == df.cycle)

(array([2, 4, 6]),)

### (6) 查找第一列的局部最大值位置：Numpy.sign()

In [12]:
#思路：查找比它前一个和后一个数字都大数字
tem = np.diff(np.sign(np.diff(df['score'])))
np.where(tem == -2)[0] + 1

array([2])

### (7) 对第二列计算移动平均值：Numpy.convolve()

- 参考资料：https://blog.csdn.net/u011599639/article/details/76254442

In [13]:
np.convolve(df['cycle'], np.ones(3)/3, mode='valid')

array([3.66666667, 4.        , 4.66666667, 3.33333333, 4.66666667,
       4.66666667])

### (8) 计算两列欧式距离：Numpy.linalg.norm()

In [14]:
#方法一：公式法
import math as mt
mt.sqrt(sum((df['score']-df['cycle'])**2))
 
#方法二：numpy函数
np.linalg.norm(df['score'] - df['cycle'])

6.6332495807108

### (9) 查找某列数据中第三大值的行号：Numpy.argsort()

In [15]:
#方法一：
df['score'].argsort()[::-1][len(df)-3]
#注：argsort() -- 从小到大排, 输出索引；[[::-1]]倒序输出 -- 即为从大到小排；
 
#方法二：先进行倒序排序，然后重置索引，取第三行第一列即为第3大值的行号
df['score'].sort_values(ascending=False).reset_index().iloc[2,0]

5

### (10)numpy其他一些统计基础函数

![image.png](https://img-blog.csdnimg.cn/20210504092647856.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM4MjMwNjYz,size_16,color_FFFFFF,t_70)

- 补充：
    - log(x + 1)：np.log1p
    - 以2为底的对数：np.log2
    - e的x次幂-1：np.expm1
    - e的次数幂：np.exp
    - 取对数：np.log
    - 开根号：np.sqrt
    - 平方：np.exp2

----


# 最后附上思维导图：

![Image Name](https://cdn.kesci.com/upload/image/quhb7y4vrd.png)

